# 全局配置
settings:
  # 当获取内容失败（如连接超时）时的重试次数。
  retry_count: 10
  # 每次重试之间的等待时间（秒）。
  retry_delay_seconds: 30
  # 是否在 Action 日志中打印 curl 命令的返回内容（用于调试）。
  log_curl_response: true
  # 需要提醒的HTTP状态码列表，当网页访问失败且状态码在此列表中时，发送变更通知
  notify_http_status_codes: [404, 403]

# 监控目标列表
targets:
  - type: "url"
    value: "https://xieqiuyi.com/XIX/user"

  - type: "url"
    value: "https://xieqiuyi.com/live/preview"

  - type: "curl"
    command: |
      curl -X GET \
        "https://xieqiuyi.com/live/messages" \
        -H "User-Agent: Preview" \
        -H "Referer: https://xieqiuyi.com/live/preview"

  - type: "url"
    value: "https://xieqiuyi.com/live/preview-status"

  - type: "url"
    value: "https://xieqiuyi.com/live/user"

  - type: "url"
    value: "https://xieqiuyi.com/XIX/admin"

  - type: "url"
    value: "https://xieqiuyi.com/XIX/get-settings"

  - type: "url"
    value: "https://xieqiuyi.com/EXIT"

  - type: "url"
    value: "https://xieqiuyi.com/activity/"

  - type: "url"
    value: "https://xieqiuyi.com/34/"


  - type: "url"
    value: "https://xieqiuyi.com/Speak/"

  - type: "url"
    value: "https://xieqiuyi.com/message/"
