targets:
  - type: "url"
    value: "https://xieqiuyi.com/XIX/user"

  - type: "url"
    value: "https://xieqiuyi.com/live/preview"

  - type: "curl"
    command: |
      curl -X GET \
        "https://xieqiuyi.com/live/messages" \
        -H "User-Agent: Preview" \
        -H "Referer: https://xieqiuyi.com/live/preview"

  - type: "url"
    value: "https://xieqiuyi.com/XIX/admin"

  - type: "url"
    value: "https://xieqiuyi.com/XIX/get-settings"

  - type: "url"
    value: "https://xieqiuyi.com/EXIT"

  - type: "url"
    value: "https://xieqiuyi.com/activity/"

  - type: "url"
    value: "https://xieqiuyi.com/34/"

  - type: "url"
    value: "https://xieqiuyi.com/Speak/"

  - type: "url"
    value: "https://xieqiuyi.com/live/user"

  - type: "url"
    value: "https://xieqiuyi.com/message/"
